spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: file:./cfg/
    security:
        user:
            name: configserver
            password: configserver
            roles: ACTUATOR_ADMIN
application:
    refreshDelayInMs: 10000
    clients:
        -
            name: pyramid-local.yml
            protocol: http
            url: localhost:8082
            user: actuator
            password: actuator
metrics:
    project: project14.config.server
    channels:
        -
            channel: external,
            ruleName: ExternalVersion,
            interval:
                - 60
                - 600
                - 3600
        -
            channel: internal,
            ruleName: InternalVersion,
            interval:
                - 60
                - 600
                - 3600
        -
            channel: scheduler,
            ruleName: ScheduleRunning,
            interval:
                - 60
                - 600
                - 3600
        -
            channel: refresh,
            ruleName: RefreshClientConfig,
            interval:
                - 60
                - 600
                - 3600
server:
    port: 8800
management:
  endpoints:
      enabled-by-default: true
      web:
          exposure:
              include: "*"
  metrics:
    export:
      prometheus:
          enabled: true
  endpoint:
    refresh:
        enabled: true
