spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: file:./cfg/
#здесь нельзя менять searchLocations на другое имя, это часть спецификации config server
    security:
        user:
            name: configserver
            password: configserver
            roles: ACTUATOR_ADMIN
application:
    refreshDelayInMs: 60000
    clients:
        -
            name: pyramid-local.yml
            protocol: http
            url: localhost:8081
            user: actuator
            password: actuator
server:
    port: 8800
management:
  endpoints:
      enabled-by-default: true
      web:
          exposure:
              include: "*"
  metrics:
    export:
      prometheus:
          enabled: true
  endpoint:
    refresh:
        enabled: true
